/**
 * LidarBuildingLayer
 *
 * Loads the pipeline output (`public/data/buildings-with-heights.geojson`)
 * and renders LiDAR-height-extruded building footprints via deck.gl.
 *
 * Generated by: python scripts/buildingPipeline.py --mode full
 *
 * Exported hook: useLidarBuildings()
 * Exported component: <LidarOverlay layers={...} />  (use inside DeckGL)
 */

import { useState, useEffect, useMemo } from 'react';
import { GeoJsonLayer } from '@deck.gl/layers';

const DATA_URL = '/data/buildings-with-heights.geojson';

// Pre-computed 256-entry LUT: dark purple → lavender by height
const HEIGHT_LUT = (() => {
  const stops = [
    [0.00, [59,   7, 100]],
    [0.33, [107, 33, 168]],
    [0.66, [147, 51, 234]],
    [1.00, [192, 132, 252]],
  ];
  return Array.from({ length: 256 }, (_, i) => {
    const t = i / 255;
    for (let j = 1; j < stops.length; j++) {
      const [t0, c0] = stops[j - 1];
      const [t1, c1] = stops[j];
      if (t <= t1) {
        const f = (t - t0) / (t1 - t0);
        return [
          Math.round(c0[0] + f * (c1[0] - c0[0])),
          Math.round(c0[1] + f * (c1[1] - c0[1])),
          Math.round(c0[2] + f * (c1[2] - c0[2])),
          210,
        ];
      }
    }
    return [192, 132, 252, 210];
  });
})();

function heightColor(heightM, isSelected, isHovered) {
  if (isSelected) return [255, 215, 30, 255];
  if (isHovered)  return [200, 220, 255, 220];
  const idx = Math.min(255, Math.round((Math.max(0, Math.min(heightM, 80)) / 80) * 255));
  return HEIGHT_LUT[idx];
}

// ── Data hook ─────────────────────────────────────────────────────────────────

export function useLidarBuildings() {
  const [data, setData]       = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);
  const [meta, setMeta]       = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch(DATA_URL)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status} — run buildingPipeline.py first`);
        return r.json();
      })
      .then(geojson => {
        if (cancelled) return;
        setData(geojson);
        setMeta(geojson.metadata || null);
        setLoading(false);
      })
      .catch(e => {
        if (!cancelled) {
          setError(e.message);
          setLoading(false);
        }
      });
    return () => { cancelled = true; };
  }, []);

  return { data, loading, error, meta };
}

// ── Layer builder ─────────────────────────────────────────────────────────────

export function buildLidarLayers({
  data,
  selectedBlocklot = null,
  hoveredBlocklot  = null,
  onHover          = () => {},
  onSelect         = () => {},
  showFeatured     = true,
}) {
  if (!data) return [];

  const allLayer = new GeoJsonLayer({
    id: 'lidar-buildings',
    data,
    pickable: true,
    extruded: true,
    wireframe: false,
    getElevation:  f => Math.max(2, f.properties.height_m || 0),
    getFillColor:  f => heightColor(
      f.properties.height_m || 0,
      f.properties.BLOCKLOT === selectedBlocklot,
      f.properties.BLOCKLOT === hoveredBlocklot,
    ),
    getLineColor:  [255, 255, 255, 18],
    lineWidthMinPixels: 0.4,
    material: {
      ambient: 0.15,
      diffuse: 0.85,
      shininess: 50,
      specularColor: [180, 180, 220],
    },
    transitions: { getFillColor: { duration: 150 } },
    updateTriggers: {
      getFillColor: [selectedBlocklot, hoveredBlocklot],
    },
    onHover: ({ object }) => onHover(object?.properties?.BLOCKLOT || null),
    onClick: ({ object }) => object && onSelect(object),
  });

  // Separate highlighted layer for featured parcel (BLOCKLOT 1976 001)
  const featuredData = showFeatured
    ? {
        ...data,
        features: data.features.filter(f => f.properties.is_featured),
      }
    : null;

  const featuredLayer = featuredData?.features?.length
    ? new GeoJsonLayer({
        id: 'lidar-featured',
        data: featuredData,
        pickable: false,
        extruded: true,
        getElevation:  f => Math.max(2, f.properties.height_m || 0) + 0.5,
        getFillColor:  [249, 115, 22, 240],   // orange-500
        getLineColor:  [251, 146, 60, 255],   // orange-400 outline
        lineWidthMinPixels: 2,
        stroked: true,
        material: {
          ambient: 0.35,
          diffuse: 1.0,
          shininess: 100,
          specularColor: [251, 146, 60],
        },
      })
    : null;

  return [allLayer, featuredLayer].filter(Boolean);
}

// ── Info badge displayed alongside the map ────────────────────────────────────

export function LidarDataBadge({ meta, loading, error }) {
  if (loading) {
    return (
      <div className="glass-panel-light px-3 py-2 text-xs text-panel-muted animate-pulse-slow">
        Loading LiDAR building data…
      </div>
    );
  }

  if (error) {
    return (
      <div className="glass-panel-light px-3 py-2 text-xs" style={{ maxWidth: 260 }}>
        <div className="text-accent-gold font-medium mb-1">LiDAR data not found</div>
        <div className="text-panel-muted leading-snug">
          Run to generate:{' '}
          <code className="font-mono text-[10px] bg-panel-bg px-1 rounded">
            python scripts/buildingPipeline.py
          </code>
        </div>
      </div>
    );
  }

  if (!meta) return null;

  const sourceShort = (meta.height_source || '')
    .replace('lidar_ndsm (', '')
    .replace(')', '');

  return (
    <div className="glass-panel-light px-3 py-2 text-[11px] space-y-1">
      <div className="flex items-center gap-1.5">
        <div className="w-1.5 h-1.5 rounded-full bg-accent-cyan" />
        <span className="text-white font-medium">LiDAR Heights Active</span>
      </div>
      <div className="text-panel-muted">
        {(meta.feature_count || 0).toLocaleString()} buildings
      </div>
      <div className="text-panel-muted" style={{ fontSize: 10 }}>
        {sourceShort || meta.height_source}
      </div>
    </div>
  );
}
